services:
  app:
    image: mysociety/uk_ruc:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /workspaces/uk_ruc      
    volumes:
      - ./:/workspaces/uk_ruc/